version: 0.0
os: linux
files:
   - source: /
     destination: /home/ubuntu/Application
permissions:
   - object: /home/ubuntu/Application
     pattern: "**"
     owner: root
     group: root
     mode: 755
     type:
       - file
hooks:
  AfterInstall:
    - location: scripts/start_service
      timeout: 180
