version: 0.0
os: linux
files:
  - source:  /
    destination: /home/ubuntu/aspnetcoreapp
  
hooks:
  ApplicationStop:
    - location: scripts/stop_service
      timeout: 300
      runas: root

  BeforeInstall:
    - location: scripts/remove_application
      timeout: 300
      runas: root
    - location: scripts/StageArtifact.ps1
    - location: scripts/CreateWebSite.ps1

  AfterInstall:
    - location: scripts/codestar_remote_access
      timeout: 300
      runas: root

    - location: scripts/install_dotnetcore
      timeout: 500
      runas: root

    - location: scripts/install_httpd
      timeout: 300
      runas: root

  ApplicationStart:
    - location: scripts/start_service
      timeout: 300
      runas: root
