version: 0.2
env:
  variables:
    PROJECT: AprioriWebApp2
    SOLUTION: .\AprioriWebApp2.sln
    PACKAGE_DIRECTORY: .\packages
    DOTNET_FRAMEWORK: 4.7.2
artifacts:
  files:
    - AprioriWebApp2/**/*
    - appspec.yml
    - ./**/*
